#!/usr/bin/node
// import node modules
var cp = require("child_process");
var fs = require("fs");
var path = require("path");

var commands = {
  member: require("./tasks/member"),
  start: require("./tasks/start"),
  build: require("./tasks/build")
}

var command = commands[process.argv[2]];

if (typeof command == "function")
  command();
else
  console.log("Please enter a valid command!");
