#!/usr/bin/node
// import node modules
var cp = require("child_process");
var fs = require("fs");
var path = require("path");

var commands = {
  member: require("./commands/member"),
  start: require("./commands/start"),
}

var command = commands[process.argv[2]];

if (typeof command == "function")
  command();
else
  console.log("Please enter a valid command!");
